### PR TITLE
Add 1.21 support

### PR DESCRIPTION
**Pull request by FlorianMichael**

### CODE REVIEW

**Review by Kichura — APPROVED** [review]
Since 4.10.x will not know what 1.21 is in general, consider limiting viaversion requirement to 5.0.0 or greater here.

Aside from this one note from earlier, lgtm.

**Comment by Wudji** [comment]
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-06-15 15:43:04
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'viafabric-mc121'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.IllegalArgumentException: displayleaks <level> is not a valid sub-command name.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
	at com.viaversion.viaversion.commands.ViaCommandHandler.registerSubCommand(ViaCommandHandler.java:54)
	at com.viaversion.viaversion.commands.ViaCommandHandler.registerDefaults(ViaCommandHandler.java:193)
	at com.viaversion.viaversion.commands.ViaCommandHandler.<init>(ViaCommandHandler.java:49)
	at com.viaversion.fabric.mc121.commands.VFCommandHandler.<init>(VFCommandHandler.java:30)
	at com.viaversion.fabric.mc121.ViaFabric.onInitialize(ViaFabric.java:81)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 10 more
```

**Comment by Kichura** [comment]
> ```
> ---- Minecraft Crash Report ----
> // Uh... Did I do that?
> 
> Time: 2024-06-15 15:43:04
> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'viafabric-mc121'!
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
> 	at net.minecraft.class_310.<init>(class_310.java:477)
> 	at net.minecraft.client.main.Main.main(Main.java:239)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
> 	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
> Caused by: java.lang.IllegalArgumentException: displayleaks <level> is not a valid sub-command name.
> 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
> 	at com.viaversion.viaversion.commands.ViaCommandHandler.registerSubCommand(ViaCommandHandler.java:54)
> 	at com.viaversion.viaversion.commands.ViaCommandHandler.registerDefaults(ViaCommandHandler.java:193)
> 	at com.viaversion.viaversion.commands.ViaCommandHandler.<init>(ViaCommandHandler.java:49)
> 	at com.viaversion.fabric.mc121.commands.VFCommandHandler.<init>(VFCommandHandler.java:30)
> 	at com.viaversion.fabric.mc121.ViaFabric.onInitialize(ViaFabric.java:81)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
> 	... 10 more
> ```

did you use any third party mods by chance? and also you can't use the public dev build with this as that is not compatible.

**Comment by kel-cu** [comment]
It crashes without additional mods as well 🤔
image

**Comment by Kichura** [comment]
> It crashes without additional mods as well 🤔 image

it's because you have to include the sponsored dev build of viaversion to your mods folder, but once viaversion 5 becomes public - it will be bumped here.

**Comment by FlorianMichael** [comment]
It crashes because your VV version is outdated

**Pull request merged**
